from decouple import config

DB_URL = config('DB_URL')

ADMIN_BOT_TOKEN = config('ADMIN_BOT_TOKEN')
CLIENT_BOT_TOKEN = config('CLIENT_BOT_TOKEN')
EMPLOYEE_BOT_TOKEN = config('EMPLOYEE_BOT_TOKEN')

DEFAULT_ADMIN_TOKEN_FOR_LOGIN = config('DEFAULT_ADMIN_TOKEN_FOR_LOGIN')
DEFAULT_EMPLOYEE_TOKEN_FOR_LOGIN = config('DEFAULT_EMPLOYEE_TOKEN_FOR_LOGIN')