"""added: admin_account

Revision ID: 22d97c7af9ce
Revises: 8554983c3b56
Create Date: 2024-11-03 13:56:59.821682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import insert
from sqlalchemy.dialects import mysql

from src import config
from src.data.logoscoffee.db.models import AdminAccountOrm

# revision identifiers, used by Alembic.
revision: str = '22d97c7af9ce'
down_revision: Union[str, None] = '8554983c3b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_account',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('token', mysql.VARCHAR(length=8), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
    )
    op.execute(
        insert(AdminAccountOrm).values(token=config.DEFAULT_ADMIN_TOKEN_FOR_LOGIN)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_account')
    # ### end Alembic commands ###
