"""init

Revision ID: 2a61db54db78
Revises: 
Create Date: 2025-01-02 21:51:41.345758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import insert

from src import config
from src.data.logoscoffee.db.models import AdminAccountOrm, EmployeeAccountOrm

# revision identifiers, used by Alembic.
revision: str = '2a61db54db78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_account',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=16), nullable=False),
    sa.Column('date_last_announcement_distributing', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('announcement',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('date_last_distribute', sa.DateTime(), nullable=True),
    sa.Column('text_content', sa.TEXT(), nullable=True),
    sa.Column('preview_photo_data', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=16), nullable=False),
    sa.Column('client_name', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('loyalty_points', sa.INTEGER(), nullable=False),
    sa.Column('date_last_review', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('token')
    )
    op.create_table('employee_account',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('event_subscriber',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.VARCHAR(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('preview_photo_data', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('text_content', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_state',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.BIGINT(), nullable=False),
    sa.Column('pickup_code', sa.VARCHAR(length=4), nullable=True),
    sa.Column('date_pending', sa.DateTime(), nullable=True),
    sa.Column('date_cooking', sa.DateTime(), nullable=True),
    sa.Column('date_ready', sa.DateTime(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('date_canceled', sa.DateTime(), nullable=True),
    sa.Column('cancel_details', sa.TEXT(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_and_order',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('product_price', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute(insert(AdminAccountOrm).values(token=config.DEFAULT_ADMIN_TOKEN_FOR_LOGIN))
    op.execute(insert(EmployeeAccountOrm).values(token=config.DEFAULT_EMPLOYEE_TOKEN_FOR_LOGIN))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_and_order')
    op.drop_table('order')
    op.drop_table('user_state')
    op.drop_table('review')
    op.drop_table('product')
    op.drop_table('event_subscriber')
    op.drop_table('employee_account')
    op.drop_table('client_account')
    op.drop_table('announcement')
    op.drop_table('admin_account')
    # ### end Alembic commands ###
