"""added: client_account

Revision ID: 401cdbb3219f
Revises: 0fe70f86cc11
Create Date: 2024-11-03 16:09:55.908814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '401cdbb3219f'
down_revision: Union[str, None] = '0fe70f86cc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(), nullable=False),
    sa.Column('date_registration', sa.Integer(), nullable=False),
    sa.Column('loyalty_points', sa.Integer(), default=0, nullable=False),
    sa.Column('date_last_review', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_account')
    # ### end Alembic commands ###
