"""alembic init

Revision ID: 6c02730af63c
Revises: 
Create Date: 2024-11-12 09:08:03.016171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import insert

from src import config
from src.data.logoscoffee.db.models import AdminAccountOrm, EmployeeAccountOrm

# revision identifiers, used by Alembic.
revision: str = '6c02730af63c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('date_authorized', sa.DateTime(), nullable=True),
    sa.Column('date_last_offer_distributing', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('client_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('date_last_review', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('employee_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('date_authorized', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('event_subscriber',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotional_offer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('date_last_distribute', sa.DateTime(), nullable=True),
    sa.Column('text_content', sa.String(), nullable=True),
    sa.Column('preview_photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('text_content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute(insert(AdminAccountOrm).values(key=config.DEFAULT_ADMIN_KEY_FOR_LOGIN))
    op.execute(insert(EmployeeAccountOrm).values(key=config.DEFAULT_EMPLOYEE_KEY_FOR_LOGIN))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_state')
    op.drop_table('review')
    op.drop_table('promotional_offer')
    op.drop_table('event_subscriber')
    op.drop_table('employee_account')
    op.drop_table('client_account')
    op.drop_table('admin_account')
    # ### end Alembic commands ###
