"""Added: RevisionOrm

Revision ID: 8d24718f164f
Revises: 401cdbb3219f
Create Date: 2024-11-06 17:48:32.216738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8d24718f164f'
down_revision: Union[str, None] = '401cdbb3219f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date_create', sa.Integer(), nullable=False),
        sa.Column('text_content', mysql.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
