"""added: event_subscriber

Revision ID: 9a4d0f084a03
Revises: e00a0a58c415
Create Date: 2024-11-10 08:15:08.489937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4d0f084a03'
down_revision: Union[str, None] = 'e00a0a58c415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_subscriber',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('user_state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_state_id'], ['user_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_subscriber')
    # ### end Alembic commands ###
