"""added: review

Revision ID: b7faf4303797
Revises: 401cdbb3219f
Create Date: 2024-11-09 00:32:19.880550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from src.data.logoscoffee.db.models import UnixTimestamp

# revision identifiers, used by Alembic.
revision: str = 'b7faf4303797'
down_revision: Union[str, None] = '401cdbb3219f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_create', UnixTimestamp(), nullable=False),
    sa.Column('text_content', mysql.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('client_account', 'date_last_review',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_account', 'date_last_review',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('review')
    # ### end Alembic commands ###
