"""added: promotional_offer

Revision ID: d18c0a3c426f
Revises: 9a4d0f084a03
Create Date: 2024-11-10 19:25:57.581589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18c0a3c426f'
down_revision: Union[str, None] = '9a4d0f084a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotional_offer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('text_content', sa.String(), nullable=True),
    sa.Column('preview_photo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotional_offer')
    # ### end Alembic commands ###
